id: opecha:P000441
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD90019
  title: རྔ་བ་ཁུལ་ས་གནས་ལོ་རྒྱུས།（རྒྱ་ཡིག
  volume:
    006799cbfc8e42f9942514631bd4c14c:
      image_group_id: I1PD90086
      title: Volume 1 of a ba zhou zhi
      volume_number: 1
      total_pages: 1046
    002147fa0b1943249d4c1333aaaeb22f:
      image_group_id: I1PD90087
      title: Volume 2 of a ba zhou zhi
      volume_number: 2
      total_pages: 1054
    d43bc577de51436a8405a0e4b0c41161:
      image_group_id: I1PD90088
      title: Volume 3 of a ba zhou zhi
      volume_number: 3
      total_pages: 1070
  author: ''
ebook_metadata:
  title: རྔ་བ་ཁུལ་ས་གནས་ལོ་རྒྱུས།（རྒྱ་ཡིག
  author: ''
  sku: P000441
  cover: cover.jpg
  layers:
  - pagination
